"""Build index.html, the gallery page, from every student card in this folder.

Instructor-only. The "Rebuild gallery" GitHub Actions workflow
(.github/workflows/build-gallery.yml) runs this automatically after every
merge to main and commits index.html. Running it by hand is optional:

    python3 build_index.py
    git add index.html && git commit -m "Update gallery" && git push

Uses only the Python standard library.
"""

import html
import re
import subprocess
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent
SKIP = {"index.html", "template.html", "template.md", "README.md", "AGENTS.md"}


def github_repo_url():
    """Return https://github.com/owner/repo from the origin remote, or None."""
    try:
        remote = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            cwd=ROOT, capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return None
    match = re.search(r"github\.com[:/](.+?)(?:\.git)?$", remote)
    return f"https://github.com/{match.group(1)}" if match else None


def find_cards():
    cards = [
        path for path in ROOT.iterdir()
        if path.is_file() and path.suffix in {".html", ".md"} and path.name not in SKIP
    ]
    return sorted(cards, key=lambda path: path.name.lower())


def card_html(path, repo_url):
    name = html.escape(path.stem)
    src = html.escape(quote(path.name))
    if path.suffix == ".html":
        # sandbox (with no allow-* flags) blocks any scripts in a student's file.
        return (
            f'<figure class="tile">\n'
            f'  <iframe sandbox src="{src}" title="{name}\'s card" loading="lazy"></iframe>\n'
            f'  <figcaption><a href="{src}">{name}</a></figcaption>\n'
            f'</figure>'
        )
    href = f"{repo_url}/blob/main/{src}" if repo_url else src
    return (
        f'<figure class="tile tile-md">\n'
        f'  <a class="md-link" href="{html.escape(href)}">📄 {name}\'s card</a>\n'
        f'  <figcaption><a href="{html.escape(href)}">{name}</a></figcaption>\n'
        f'</figure>'
    )


PAGE = """<!DOCTYPE html>
<!-- Generated by build_index.py — do not edit by hand. -->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Profiles Gallery — Fall 2026</title>
  <style>
    :root {{
      --bg: #0f172a;
      --card: #1e293b;
      --text: #f1f5f9;
      --muted: #94a3b8;
      --accent: #38bdf8;
    }}

    * {{
      box-sizing: border-box;
    }}

    body {{
      margin: 0;
      padding: 2rem 1rem;
      background: var(--bg);
      color: var(--text);
      font-family: system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    }}

    header {{
      text-align: center;
      margin-bottom: 2rem;
    }}

    h1 {{
      margin: 0;
    }}

    header p {{
      margin: 0.5rem 0 0;
      color: var(--muted);
    }}

    .grid {{
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(min(100%, 420px), 1fr));
      gap: 1.5rem;
      max-width: 1400px;
      margin: 0 auto;
    }}

    .tile {{
      margin: 0;
      display: flex;
      flex-direction: column;
    }}

    .tile iframe {{
      width: 100%;
      height: 480px;
      border: 0;
      border-radius: 16px;
    }}

    .tile-md .md-link {{
      display: grid;
      place-items: center;
      height: 480px;
      background: var(--card);
      border: 2px dashed var(--muted);
      border-radius: 16px;
      color: var(--text);
      font-size: 1.25rem;
      text-decoration: none;
    }}

    figcaption {{
      text-align: center;
      margin-top: 0.5rem;
    }}

    a {{
      color: var(--accent);
    }}

    .empty {{
      text-align: center;
      color: var(--muted);
    }}
  </style>
</head>
<body>
  <header>
    <h1>Profiles Gallery — Fall 2026</h1>
    <p>{count}</p>
  </header>
  <main>
{body}
  </main>
</body>
</html>
"""


def main():
    cards = find_cards()
    if cards:
        repo_url = github_repo_url()
        tiles = "\n".join(card_html(path, repo_url) for path in cards)
        body = '    <div class="grid">\n' + "\n".join(
            "      " + line for line in tiles.splitlines()
        ) + "\n    </div>"
        count = f"{len(cards)} card{'s' if len(cards) != 1 else ''}"
    else:
        body = '    <p class="empty">No cards yet — be the first to open a pull request!</p>'
        count = "0 cards"
    (ROOT / "index.html").write_text(PAGE.format(count=count, body=body), encoding="utf-8")
    print(f"Wrote index.html with {count}.")


if __name__ == "__main__":
    main()
