"""Build index.html, the gallery page, from every student card in the CARDS_DIR folder.

Instructor-only. The "Rebuild gallery" GitHub Actions workflow
(.github/workflows/build-gallery.yml) runs this automatically after every
merge to main and commits index.html. Running it by hand is optional:

    python3 build_index.py
    git add index.html && git commit -m "Update gallery" && git push

Uses only the Python standard library.
"""

import html
import re
import subprocess
import zlib
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent
CARDS_DIR = "profiles"
GITHUB_PROFILE = "https://github.com"  # + "/USERNAME"; cards are named after GitHub usernames

# Show a "your card goes here" placeholder tile until the gallery fills up.
GHOST_TILE_BELOW = 4


def github_repo_url():
    """Return https://github.com/owner/repo from the origin remote, or None."""
    try:
        remote = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            cwd=ROOT, capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return None
    match = re.search(r"github\.com[:/](.+?)(?:\.git)?$", remote)
    return f"https://github.com/{match.group(1)}" if match else None


def find_cards():
    folder = ROOT / CARDS_DIR
    if not folder.is_dir():
        return []
    cards = [
        path for path in folder.iterdir()
        if path.is_file() and path.suffix in {".html", ".md"}
    ]
    return sorted(cards, key=lambda path: path.name.lower())


ARROW = (
    '<svg viewBox="0 0 16 16" width="14" height="14" fill="none" stroke="currentColor" '
    'stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
    '<path d="M5 11 11 5M6 5h5v5"/></svg>'
)

DOC = (
    '<svg viewBox="0 0 48 48" width="56" height="56" fill="none" stroke="currentColor" '
    'stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
    '<path d="M12 5h16l10 10v27a1 1 0 0 1-1 1H12a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1Z"/>'
    '<path d="M28 5v10h10M17 26h14M17 32h14M17 20h5"/></svg>'
)


def avatar_hue(username):
    """A stable 0-359 hue per username, so each avatar gets its own color."""
    return zlib.crc32(username.lower().encode("utf-8")) % 360


def caption_html(path, href):
    name = html.escape(path.stem)
    initial = html.escape(path.stem[:1].upper())
    profile = html.escape(f"{GITHUB_PROFILE}/{quote(path.stem)}")
    return (
        f'<figcaption class="who">\n'
        f'    <a class="person" href="{profile}" title="{name} on GitHub">\n'
        f'      <span class="avatar" style="--hue: {avatar_hue(path.stem)}" aria-hidden="true">{initial}</span>\n'
        f'      <span class="name">{name}</span>\n'
        f'    </a>\n'
        f'    <a class="open" href="{href}">Open card {ARROW}</a>\n'
        f'  </figcaption>'
    )


def card_html(path, repo_url):
    name = html.escape(path.stem)
    rel = path.relative_to(ROOT).as_posix()
    src = html.escape(quote(rel))
    if path.suffix == ".html":
        # sandbox (with no allow-* flags) blocks any scripts in a student's file.
        return (
            f'<figure class="tile">\n'
            f'  <div class="stage">\n'
            # tabindex="-1": the caption's "Open card" link is the keyboard stop for this tile.
            f'    <iframe sandbox src="{src}" title="{name}\'s card" loading="lazy" tabindex="-1"></iframe>\n'
            f'  </div>\n'
            f'  {caption_html(path, src)}\n'
            f'</figure>'
        )
    href = html.escape(f"{repo_url}/blob/main/{src}" if repo_url else src)
    return (
        f'<figure class="tile tile-md">\n'
        f'  <a class="stage md-link" href="{href}">\n'
        f'    {DOC}\n'
        f'    <span class="md-title">{name}\'s card</span>\n'
        f'    <span class="md-note">Markdown card &middot; opens on GitHub</span>\n'
        f'  </a>\n'
        f'  {caption_html(path, href)}\n'
        f'</figure>'
    )


def ghost_html():
    return (
        f'<div class="tile tile-ghost">\n'
        f'  <div class="stage ghost">\n'
        f'    <span class="ghost-plus" aria-hidden="true">+</span>\n'
        f'    <span class="ghost-title">Your card goes here</span>\n'
        f'    <code>profiles/YOUR-USERNAME.html</code>\n'
        f'    <span class="ghost-note">Fork &rarr; branch &rarr; pull request</span>\n'
        f'  </div>\n'
        f'</div>'
    )


PAGE = """<!DOCTYPE html>
<!-- Generated by build_index.py — do not edit by hand. -->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Profiles Gallery — Fall 2026</title>
  <style>
    :root {
      --bg: #0f172a;
      --card: #1e293b;
      --text: #f1f5f9;
      --muted: #94a3b8;
      --accent: #38bdf8;
      --line: rgba(148, 163, 184, 0.28);
    }

    * {
      box-sizing: border-box;
    }

    body {
      margin: 0;
      min-height: 100vh;
      padding: clamp(1.5rem, 4vw, 3.5rem) 1.25rem 2.5rem;
      background-color: var(--bg);
      background-image: radial-gradient(rgba(148, 163, 184, 0.16) 1px, transparent 1px);
      background-size: 26px 26px;
      color: var(--text);
      font-family: system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      line-height: 1.5;
    }

    a {
      color: inherit;
    }

    :focus-visible {
      outline: 3px solid var(--accent);
      outline-offset: 3px;
    }

    /* ---------- Header ---------- */

    .hero {
      max-width: 60rem;
      margin: 0 auto clamp(2rem, 5vw, 3.5rem);
      text-align: center;
    }

    .kicker {
      margin: 0 0 0.9rem;
      color: var(--muted);
      font-size: 1rem;
      font-weight: 600;
      letter-spacing: 0.14em;
      text-transform: uppercase;
    }

    h1 {
      margin: 0;
      font-size: clamp(2.5rem, 7vw, 4.75rem);
      font-weight: 800;
      line-height: 1.05;
      letter-spacing: -0.035em;
    }

    h1 span {
      color: var(--accent);
    }

    .count {
      display: inline-flex;
      align-items: center;
      gap: 0.5rem;
      margin: 1.5rem 0 0;
      padding: 0.4rem 1.1rem;
      border: 1px solid var(--line);
      border-radius: 999px;
      background: rgba(30, 41, 59, 0.7);
      color: var(--muted);
      font-size: 1.15rem;
    }

    .count strong {
      color: var(--text);
      font-size: 1.35rem;
      font-variant-numeric: tabular-nums;
    }

    /* ---------- Grid and tiles ---------- */

    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(min(100%, 380px), 440px));
      justify-content: center;
      gap: clamp(1.25rem, 3vw, 2rem);
    }

    .tile {
      margin: 0;
      display: flex;
      flex-direction: column;
      gap: 0.75rem;
    }

    .stage {
      position: relative;
      height: 480px;
      overflow: hidden;
      border: 1px solid var(--line);
      border-radius: 20px;
      background: var(--card);
      box-shadow: 0 18px 40px -18px rgba(0, 0, 0, 0.7);
      transition: transform 0.25s ease, border-color 0.25s ease, box-shadow 0.25s ease;
    }

    .tile:hover .stage,
    .tile:focus-within .stage {
      transform: translateY(-4px);
      border-color: var(--accent);
      box-shadow: 0 24px 48px -18px rgba(0, 0, 0, 0.8), 0 0 0 1px var(--accent);
    }

    .stage iframe {
      display: block;
      width: 100%;
      height: 100%;
      border: 0;
    }

    /* ---------- Caption ---------- */

    .who {
      display: flex;
      align-items: center;
      gap: 0.7rem;
      padding: 0.35rem 0.75rem 0.35rem 0.6rem;
    }

    .person {
      display: flex;
      flex: 1;
      align-items: center;
      gap: 0.7rem;
      min-width: 0;
      border-radius: 999px;
      text-decoration: none;
    }

    .person:hover .name {
      text-decoration: underline;
      text-underline-offset: 0.2em;
    }

    .avatar {
      display: grid;
      place-items: center;
      flex: none;
      width: 2.75rem;
      height: 2.75rem;
      border-radius: 50%;
      /* --hue is set per student by build_index.py; light enough for dark text. */
      background: hsl(var(--hue, 199) 80% 70%);
      color: #0b1220;
      font-size: 1.25rem;
      font-weight: 800;
    }

    .name {
      flex: 1;
      min-width: 0;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
      font-size: 1.4rem;
      font-weight: 700;
    }

    .open {
      display: inline-flex;
      flex: none;
      align-items: center;
      gap: 0.3rem;
      border-radius: 999px;
      color: var(--muted);
      font-size: 1.05rem;
      text-decoration: none;
      transition: color 0.2s ease;
    }

    .open:hover,
    .open:focus-visible {
      color: var(--text);
    }

    /* ---------- Markdown and placeholder tiles ---------- */

    .md-link {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      gap: 0.6rem;
      background: var(--card);
      color: var(--accent);
      text-decoration: none;
    }

    .md-title {
      color: var(--text);
      font-size: 1.5rem;
      font-weight: 700;
    }

    .md-note {
      color: var(--muted);
      font-size: 1rem;
    }

    .ghost {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      gap: 0.6rem;
      border: 2px dashed var(--line);
      background: transparent;
      box-shadow: none;
      text-align: center;
    }

    .ghost-plus {
      display: grid;
      place-items: center;
      width: 3.5rem;
      height: 3.5rem;
      border: 2px dashed var(--accent);
      border-radius: 50%;
      color: var(--accent);
      font-size: 2rem;
      line-height: 1;
    }

    .ghost-title {
      font-size: 1.5rem;
      font-weight: 700;
    }

    .ghost code {
      padding: 0.2rem 0.6rem;
      border-radius: 8px;
      background: var(--card);
      color: var(--accent);
      font-size: 1rem;
    }

    .ghost-note {
      color: var(--muted);
      font-size: 1rem;
    }

    .empty {
      max-width: 32rem;
      margin: 0 auto;
      padding: 3rem 1.5rem;
      border: 2px dashed var(--line);
      border-radius: 20px;
      color: var(--muted);
      font-size: 1.15rem;
      text-align: center;
    }

    @media (prefers-reduced-motion: reduce) {
      .stage,
      .open {
        transition: none;
      }

      .tile:hover .stage,
      .tile:focus-within .stage {
        transform: none;
      }
    }
  </style>
</head>
<body>
  <header class="hero">
    <p class="kicker">UW Bothell &middot; Fall 2026 &middot; Git &amp; GitHub workshop</p>
    <h1>Profiles <span>Gallery</span></h1>
    <p class="count"><strong>@@NUMBER@@</strong> @@UNIT@@</p>
  </header>
  <main>
@@BODY@@
  </main>
</body>
</html>
"""


def main():
    cards = find_cards()
    repo_url = github_repo_url()
    if cards:
        tiles = [card_html(path, repo_url) for path in cards]
        if len(cards) < GHOST_TILE_BELOW:
            tiles.append(ghost_html())
        body = '    <div class="grid">\n' + "\n".join(
            "      " + line for line in "\n".join(tiles).splitlines()
        ) + "\n    </div>"
    else:
        body = '    <p class="empty">No cards yet — be the first to open a pull request!</p>'
    unit = "card" if len(cards) == 1 else "cards"
    page = (
        PAGE.replace("@@NUMBER@@", str(len(cards)))
        .replace("@@UNIT@@", unit)
        .replace("@@BODY@@", body)
    )
    (ROOT / "index.html").write_text(page, encoding="utf-8")
    print(f"Wrote index.html with {len(cards)} {unit} from {CARDS_DIR}/.")


if __name__ == "__main__":
    main()
